nelmio_cors:
    defaults:
        allow_origin: ['*']  # Autorise toutes les origines, vous pouvez spécifier des domaines au lieu de '*' si nécessaire
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PATCH']  # Méthodes HTTP autorisées
        allow_headers: ['Content-Type', 'Authorization']  # En-têtes autorisés
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':  # Applique la configuration à toutes les routes API
            allow_origin: ['*']  # Autorise toutes les origines pour les API
            allow_methods: ['GET', 'POST', 'PATCH', 'OPTIONS']  # Méthodes autorisées
            allow_headers: ['Content-Type', 'Authorization']  # En-têtes autorisés
